version: "3"

services:
  hugo:
    build:
      context: .
      dockerfile: ./docker/hugo/Dockerfile
    container_name: docker_template_hugo_container
    environment:
      - TZ=Japan
    ports:
      - "1313:1313"
    stdin_open: true
    tty: true
    volumes:
      - ./site:/usr/src/site
    working_dir: /usr/src/site
