version: "3"

services:
  hugo:
    image: klakegg/hugo:0.111.3-alpine
    command: server --bind=0.0.0.0 --buildDrafts
    container_name: docker_template_hugo_container
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "1313:1313"
    stdin_open: true
    tty: true
    volumes:
      - ./site:/usr/src/site
    working_dir: /usr/src/site
